version: '3'
services:
  continuum-auth:
    build:
      context: "."
      dockerfile: 'Dockerfile'
      args:
        image_tag: ${IMAGE_TAG:-local}
    image: libero/continuum-auth:${IMAGE_TAG:-local}
