version: '3'
services:
  continuum-adaptor:
    image: libero/continuum-adaptor:${IMAGE_TAG:-local}
    container_name: test_continuum_adaptor
    ports:
      - "3001:3000"
    environment: 
      PORT: 3000
      RABBITMQ_URL: rabbitmq
      LOGIN_URL: http://localhost:9000/submit
      LOGIN_RETURN_URL: http://localhost:9000/login
      AUTHENTICATION_JWT_SECRET: super_secret_jam
      CONTINUUM_JWT_SECRET: some_secret_from_journal
      CONTINUUM_API_URL: http://reviewer-mocks:3003
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      ELIFE_API_GATEWAY_SECRET: ${ELIFE_API_GATEWAY_SECRET}
    healthcheck:
      test: 'echo -e "GET /health\n\n" | nc localhost 3000'
      interval: 10s
      timeout: 10s
      retries: 3
    depends_on:
      - rabbitmq
      - reviewer-mocks

  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:latest
    container_name: test_reviewer_mocks
    ports:
      - "${REVIEWER_MOCKS_PORT:-3003}:3003"
    environment: 
      DATA_DIRECTORY_PATH: "/etc/mock-data/"
    volumes:
      - ./tests/config/reviewer-mocks.json:/etc/reviewer/config.json:z
      - ./tests/mock-data:/etc/mock-data/ 
    healthcheck:
      test: 'echo -e "GET /health\n\n" | nc localhost ${REVIEWER_MOCKS_PORT:-3003}'
      interval: 10s
      timeout: 10s
      retries: 3

  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: test_rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 2s
      timeout: 30s
      retries: 10

  postgres:
    image: liberoadmin/reviewer-xpub-postgres:latest
    container_name: test_postgres
    environment: 
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 30s
      retries: 10
