version: '3'
services:
  continuum-adaptor:
    image: node:10
    ports:
      - "${CONTINUUM_AUTH_PORT:-3001}:3001"
    working_dir: "/src"
    healthcheck:
      test: "curl localhost:3001/health"
      interval: 1m
      timeout: 10s
      retries: 3
    command: ["bash", "-c", "yarn && yarn run start:dev"]
    environment: 
      CONFIG_PATH: /etc/reviewer/config.json
    volumes:
      - ./:/src/:z
      - ./config/:/etc/reviewer/:z