version: '3'
services:
  continuum-adaptor:
    build:
      context: "."
      dockerfile: 'Dockerfile'
      args:
        image_tag: ${IMAGE_TAG:-local}
    image: libero/continuum-adaptor:${IMAGE_TAG:-local}
