version: '3'
services:
  continuum-adaptor:
    image: node:12-alpine@sha256:5646d1e5bc470500414feb3540186c02845db0e0e1788621c271fbf3a0c1830d
    working_dir: "/src"
    command: ["sh", "-c", "yarn && yarn run start:dev"]
    ports:
      - '3001:3001'
    healthcheck:
      test: "curl localhost:3001/health"
      interval: 1m
      timeout: 10s
      retries: 3
    environment: 
      PORT: 3001
      RABBITMQ_URL: rabbitmq
      LOGIN_URL: http://localhost:9000/submit
      LOGIN_RETURN_URL: http://localhost:3003/redirect_location_for_intergration_test
      AUTHENTICATION_JWT_SECRET: super_secret_jam
      CONTINUUM_JWT_SECRET: some_secret_from_journal
      CONTINUUM_API_URL: http://reviewer-mocks:3003
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      ELIFE_API_GATEWAY_SECRET: ${ELIFE_API_GATEWAY_SECRET}
    networks:
      - "reviewer"
    volumes:
      - ./:/src/:z

networks:
  reviewer:
    external:
      name: "reviewer"


